# /etc/nixos/lukskeyfile.nix (Don't forget to add it to configuration.nix)
# The minimal config required for a luksencrypted root with a keyfile
# You can skip this file if you use a passphrase
{ config, lib, pkgs, ... }:
{
  # remove if you do not use an usb-stick with a keyfile
  boot.kernelModules = [ "usb_storage" ];
  boot.extraModulePackages = [ ];

  boot.initrd.network = {
    enable = true;
    ssh = {
      enable = true;
      authorizedKeys = [ "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDheFDdl/j4lEDPmlvq0SFymOwOvkROkCjehILUb4JdjsSx7Ftk/FVxuJf1aNaItogatbQ6HeEzIeqIZwO81yHyMeS05ALsJJQ6aG6+9BbNHYCwqUAhjsXjJR00F5lbLme38mfKCf4IMsfX1YCP/Hv6tUmyBzEl/vOLkAulZplrSKpu7nWSYoDP3H/26c638RFU1sGyyZ/UG9C6BuEDj8w4w3nEEkx/SqGgs7Gji2IUa4FeUc9rcju48MR2Q/K7dMuwAY5R87ZdYcGO9RVlCU1z1rwUXpT5VxObey6+pb9o8u4uUAsj8g7WwyocuG9/odNP3zZ8H/CkyxQwYhfEAb9AVmbNbETJ12rvDjdD9i3w5KVuWGEAeBVdfzfUK6HxMYjTXMEGQY2jZgHeA3mwVNrW8pNmzoc3SxovLp7SOn617QcpLjebSwqUuW9Mcrrv23gL9lxmXBOiU06+g7IBUrp+JLGqnd2Lrzcv4w+3QHmJqTWsLAdi8q0fGIdrJEB8z4tF3Vy7QqstehSMEN2boZ+3E0gzaY+2Ze7RPUc0V6Kg4SvmOP/ikTTEw5DfXboBIyPV+Xy8ljzkTj0pQcBSYmYI5ms6HQ2ccTLURjocnWpRm27LRVSli1UzbuboAChORqPfj1E6URYncz72VIKwfG1KhhBe0Qr42EnYo/tv01cFiQ== Generated By Termius" ];
      hostRSAKey = "/etc/techhazard/hostkey";

    };
  };

  boot.initrd.luks.devices."nixroot" = {
    keyFile = "/path/to/keyfile";
    keyFileSize = keyfile_size_here;
  };
}
